# Generated by Django 6.0 on 2025-12-31 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeUniversitaire',
            fields=[
                ('id_annee', models.BigAutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'annee_universitaire',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompositionJury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'composition_jury',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id_departement', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_departement', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'departement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Encadrement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encadrement', models.CharField(choices=[('ENCADRANT', 'ENCADRANT'), ('CO_ENCADRANT', 'CO_ENCADRANT')], default='ENCADRANT', max_length=40)),
            ],
            options={
                'db_table': 'encadrement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id_etudiant', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=60)),
                ('prenom', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=120, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=30, null=True)),
                ('filiere', models.CharField(blank=True, max_length=80, null=True)),
                ('niveau', models.CharField(blank=True, max_length=50, null=True)),
                ('mot_de_pass', models.TextField()),
            ],
            options={
                'db_table': 'etudiant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id_grade', models.BigAutoField(primary_key=True, serialize=False)),
                ('libelle_grade', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'db_table': 'grade',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jury',
            fields=[
                ('id_jury', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_jury', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'db_table': 'jury',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Memoire',
            fields=[
                ('id_memoire', models.BigAutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('PFE', 'PFE'), ('MEMOIRE', 'MEMOIRE'), ('RAPPORT', 'RAPPORT'), ('THESE', 'THESE')], max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('fichier_pdf', models.TextField(blank=True, null=True)),
                ('date_depot', models.DateTimeField()),
                ('statut', models.CharField(choices=[('DEPOSE', 'DEPOSE'), ('EN_VERIFICATION', 'EN_VERIFICATION'), ('VALIDE', 'VALIDE'), ('REFUSE', 'REFUSE')], default='DEPOSE', max_length=20)),
            ],
            options={
                'db_table': 'memoire',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id_niveau', models.BigAutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'niveau',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id_note', models.BigAutoField(primary_key=True, serialize=False)),
                ('note_finale', models.DecimalField(decimal_places=2, max_digits=4)),
                ('commentaire', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'note',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id_responsable', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=60)),
                ('prenom', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=120, unique=True)),
                ('role', models.CharField(choices=[('ADMIN', 'ADMIN'), ('ENCADRANT', 'ENCADRANT'), ('RAPPORTEUR', 'RAPPORTEUR'), ('PRESIDENT', 'PRESIDENT'), ('MEMBRE_JURY', 'MEMBRE_JURY')], default='ENCADRANT', max_length=40)),
                ('mot_de_pass', models.TextField()),
            ],
            options={
                'db_table': 'responsable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id_salle', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom_salle', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'db_table': 'salle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Soutenance',
            fields=[
                ('id_soutenance', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(db_column='date_')),
                ('heure', models.TimeField()),
                ('statut', models.CharField(choices=[('PLANIFIEE', 'PLANIFIEE'), ('EFFECTUEE', 'EFFECTUEE'), ('ANNULEE', 'ANNULEE')], default='PLANIFIEE', max_length=20)),
            ],
            options={
                'db_table': 'soutenance',
                'managed': False,
            },
        ),
    ]
